name: break_your_keyboard
description: A multiplayer game to keep clicking on the keyboard and revenge

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  get_it: ^5.0.1
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  strict_dart: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Cabin-VariableFont_wdth,wght.ttf
